### ISSUE TITLE
SEHException when disposing SafeHandle obtained from LoadImage

### ISSUE THREAD

**Issue by x3ntrix** [microsoft/CsWin32#715]
## Actual behavior

When using LoadImage to load the application icon from an executable, the returned SafeHandle causes an SEHException when it is disposed.

Message: External component has thrown an exception
Stacktrace: 
```
   at Microsoft.Win32.Win32Native.CloseHandle(IntPtr handle)
   at System.Runtime.InteropServices.SafeHandle.InternalDispose()
```

## Expected behavior

No exception.

## Repro steps

1. `NativeMethods.txt` content:
```
LoadImage
LoadLibraryEx
```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?
```
using var moduleHandle = PInvoke.LoadLibraryEx("<pathToExecutable>", null, LOAD_LIBRARY_FLAGS.LOAD_LIBRARY_AS_DATAFILE);
var iconHandle = PInvoke.LoadImage(moduleHandle, "#32512", GDI_IMAGE_TYPE.IMAGE_ICON, 256, 256, IMAGE_FLAGS.LR_SHARED);
iconHandle.Dispose(); // causes SEHException
```

### Context

- CsWin32 version: 0.2.63-beta
- Win32Metadata version (if explicitly set by project):
- Target Framework: net48
- `LangVersion` (if explicitly set by project): latest

**Comment by AArnott** [comment]
This is because although `LoadImage` in native code returns `HANDLE`, it is inappropriate to release the handle with `CloseHandle`. The workaround is to avoid the `SafeHandle` method overload, like this:

```cs
unsafe
{
    fixed (char* pName = "#32512")
    {
        using var moduleHandle = PInvoke.LoadLibraryEx("<pathToExecutable>", null, LOAD_LIBRARY_FLAGS.LOAD_LIBRARY_AS_DATAFILE);
        var iconHandle = (HICON)(IntPtr)PInvoke.LoadImage((HINSTANCE)moduleHandle.DangerousGetHandle(), pName, GDI_IMAGE_TYPE.IMAGE_ICON, 256, 256, IMAGE_FLAGS.LR_SHARED);
        GC.KeepAlive(moduleHandle); // this keeps the module alive while in the above call

        // Use the icon here.

        PInvoke.DestroyIcon(iconHandle);
    }
}
```

The metadata should be updated to indicate that `LoadImage`'s return type isn't reliable for purposes of handle disposal. I'll file a bug about that.

Related issues: #199

**Comment by AArnott** [comment]
Turns out the metadata was already tracking this with https://github.com/microsoft/win32metadata/issues/611

We'll keep this issue as active and blocked on that metadata issue.

**Comment by x3ntrix** [comment]
@AArnott, thanks for the fast response. I came up with a similar workaround in the meantime. But according to the documentation and the linked issue, `PInvoke.DestroyIcon` should not be called in this case because `IMAGE_FLAGS.LR_SHARED` is used.

I don't understand why `GC.KeepAlive(moduleHandle)` is necessary. Shouldn't it be kept alive until the end of the current block, where it will be disposed? Could you please explain or tell me where I can find further information?

**Comment by AArnott** [comment]
Good points. In general the `KeepAlive` is required because the GC might run, find the `moduleHandle` isn't used any more (since the `LoadImage`  call had already been started), and finalize it. The finalization would release the handle, and potentially break `LoadImage` in a very difficult timing bug. KeepAlive prevents this. But since you declare moduleHandle with a `using` in front, it _must_ retain a reference till that `using` is closed, so it can't be GC'd.
I've updated my code to account for your two observations.

**Comment by x3ntrix** [comment]
Thanks for the explanation.

**Comment by mikebattista** [comment]
I just fixed the metadata bug so you should be able to fix this with the next update.

**Comment by x3ntrix** [comment]
I finally found some time to look at it again. The problem still exists with version 0.3.18-beta.

**Comment by AArnott** [comment]
@mikebattista I am looking at v54 of the metadata and I don't see any attributes that would solve this:

```cs
[DllImport("USER32.dll", ExactSpelling = true, PreserveSig = false, SetLastError = true)]
[SupportedOSPlatform("windows5.0")]
[Unicode]
[Documentation("https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-loadimagew")]
public static extern HANDLE LoadImageW([Optional][In] HINSTANCE hInst, [In][Const] PWSTR name, [In] GDI_IMAGE_TYPE type, [In] int cx, [In] int cy, [In] IMAGE_FLAGS fuLoad);

[RAIIFree("CloseHandle")]
[InvalidHandleValue(-1L)]
[InvalidHandleValue(0L)]
[NativeTypedef]
public struct HANDLE
{
	public IntPtr Value;
}
```

From [the fixing commit](https://github.com/microsoft/win32metadata/commit/29d57230e8111e6fecca637ee217bd9c2a75a862) I would have guessed we were going to get a `LOADIMAGE_HANDLE`, but that type isn't defined an the return type on the method is still `HANDLE`. 
Further, nowadays I suspect the better solution would be a `[return: DoNotRelease]` attribute on each affected method, but I don't see that either.

**Comment by jevansaks** [comment]
Tracked by https://github.com/microsoft/win32metadata/issues/611. Once that's resolved, this will be fixed.
